version: '3.8'

services:
  app:
    image: kiii_app:v2
    build:
      context: .
    container_name: kiii_app
    depends_on:
      - db
    ports:
      - "9091:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lab_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  db:
    image: postgres:13
    container_name: lab_postgres_db
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
